### ISSUE TITLE
Lan Anh báo cáo tiến độ công việc tháng 3

### ISSUE THREAD

**Issue by Zugor** [TTATTT/Detect_SmartIR#1]
- Project này em đã làm những gì?

- Đạt được kết quả ra sao?

**Comment by lananhlala** [comment]
Các công việc đã làm:
- Tìm hiểu bài toán phát hiện hành vi bất thường sử dụng Machine Learning
- Nghiên cứu source code cũ
- Modify source code
- Chạy thử bài toán với các mô hình học máy cơ bản như: Naive Bayes, Logistic Regression, K nearest neighbor
- Đánh giá các mô hình: chia làm 2 tập train và test, Logistic Regression cho kết quả đánh giá trên tập test là tốt nhất,
    nhưng model Naive Bayes cho kết quả ổn định hơn (do tính toán dựa trên xác suất)
Ngoài ra:
- Làm quen với elasticsearch: các khái niệm cơ bản như cluster, node,... và cách thức hoạt động

**Comment by Zugor** [comment]
Công việc của em trong tháng tới:

- Tiếp tục nghiên cứu và cải thiện thuật toán cho bài toán phát hiện hành vi bất thường sử dụng Machine Learning. Nếu cần bổ sung hay yêu cầu gì (vd thêm dữ liệu) thì đề bạt với anh.
- Tìm hiểu thêm ứng dụng AI vào dữ liệu Logs ( web access, error, log hệ thống, process, network,... )
hoặc liên quan tới Security
- Lập trình Django

**Comment by lananhlala** [comment]
- Bài toán hành vi bất thường em sẽ thử với các mô hình Deep learning ạ, tuy nhiên do kiến thức chưa có nhiều nên em sẽ giành thêm thời gian để nghiên cứu và áp dụng ạ.
- Về ứng dụng AI vào dữ liệu logs nếu có khó khăn trong quá trình tìm hiểu em sẽ chủ động hỏi ạ
- Định hướng của em là Machine learning và back end ạ, nên em mong sẽ được học hỏi thêm về lập trình backend ạ
